### PR TITLE
WebCatalog 6: Pro Features

### PR DESCRIPTION
**Pull request by quanglam2807**
- [x] Adds connection error notice.
- [x] Disables nodeIntegration in renderer to improve security.
- [x] Adds tab support #62 #87 .
- [x] Adds right-click menu #102.

screen shot 2017-06-08 at 8 10 38 pm

screen shot 2017-06-08 at 8 10 50 pm

### CODE REVIEW

**Comment by quanglam2807** [comment]
@natrim @markcea @fatihturan @camcraig @cmer New build is up. Please test 
https://github.com/webcatalog/webcatalog/releases/tag/v6.0.0-beta

**Comment by natrim** [comment]
the remember last open does not work anymore

and could you make the right click menu disablable? i use custom right click menu to handle nav

**Comment by quanglam2807** [comment]
Thanks a lot, @natrim. It should be fixed. Also, you can use `window.oncontextmenu` instead of `addEventListener('contextmenu',..` to overwrite the default behavior.

New build: https://github.com/webcatalog/webcatalog/releases/tag/v6.0.0-beta.2

@natrim @markcea

**Comment by natrim** [comment]
ok, thanks for the override for contextmenu

one more thing about remember last page, it saves the last page on domready or something like that
so sometimes happen that when you reopen the app it displays wrong page
it would probably be better to save the last page in navigation start

then with the new tab feature it sometimes happens that the app displays horizontal scroll even when is not really needed, it seems the page is resizing bit weirdly (ie. on Dropbox Paper login page)

plus the separate tab removed old saved data from v5, which i can live with but it would be nice to be able to have shared data between tabs when needed, ie. to have open different documents in each tab without the need to login in each one

**Comment by natrim** [comment]
the tabs feature is causing that the app forgets all saved cookies and forces me to relogin to apps 
it happens irregulary, probadly after computer exit?

**Comment by quanglam2807** [comment]
@natrim New build: https://github.com/webcatalog/webcatalog/releases/tag/v6.0.0-beta.3

I'll merge this PR into `master` branch to start working on v7. I think I won't bring 6.0 to the production stage.

**Comment by natrim** [comment]
ok, btw with beta.3 the session gets lost immediately after quitting the app

**Comment by quanglam2807** [comment]
@natrim I think there's a bug in the code. If you close all the tabs and open them again, maybe it would work normally.

**Comment by natrim** [comment]
nope, totally like broken

**Pull request merged**
