### PR TITLE
WebCatalog 8: Removing Centralized Server

### PR DESCRIPTION
**Pull request by quanglam2807**
To make the project more sustainable, I'll remove most of the server-based features: account, top charts, new apps, etc. 

Server-based app directory will also be removed. A small number of popular apps will be listed in the new version. For other apps, users can the new feature to create custom app. #113

### CODE REVIEW

**Comment by quanglam2807** [comment]
@cotfas @swrobel @demicon @ianjukes Can you guys test the new version: https://github.com/webcatalog/webcatalog/releases/tag/v8.0.0, please :)?

**Comment by swrobel** [comment]
@quanglam2807 I installed on my Mac and all of my already installed apps say "This app is no longer supported." Do I need to reinstall all apps?

**Comment by quanglam2807** [comment]
@quanglam2807 You do. In WebCatalog 7, the icons are downloaded from the server. In WebCatalog 8, they are stored locally. :)

**Comment by swrobel** [comment]
I see you've released 8.0 👏 

I tested multiple scenarios including a custom app with a transparent png icon and everything worked great. The only annoying thing was that I had to uninstall & reinstall all apps, but I didn't have to log into any of them again after reinstalling which is great. Still, to avoid getting a lot of support questions you may want to add an easy way to do this process for all installed apps, or at least a detailed upgrade note.

**Comment by quanglam2807** [comment]
@swrobel Thanks a lot!! I've updated the `RELEASE_NOTES.md` https://github.com/webcatalog/webcatalog/blob/master/RELEASE_NOTES.md. I could have done much better but it's too late :(

**Comment by ianjukes** [comment]
So I think version 8 is a huge improvement. Good job Quang.

**Pull request merged**
