### PR TITLE
4.1: Polishing

### PR DESCRIPTION
**Pull request by quanglam2807**
- [x] #60 
- [x] #82 
- [x] #69 
- [x] #94 => Temporarily removed custom app feature.
- [x] Improve notification.
- [x] Improve update mechanism.

### CODE REVIEW

**Comment by quanglam2807** [comment]
@natrim @Paulser 4.1.2 is up. Please test. https://github.com/webcatalog/webcatalog/releases/tag/v4.1.2

**Comment by natrim** [comment]
app install still not working it just writes to console and nothing happens

`Checking for update`
`No update available`

the same with app update, it just gets stuck

plus some icons are not loaded, though if i look on the url then the url is ok, probably some problem with loading too many images (this happens only sometimes)

plus there is some error in console on running the apps

`Uncaught TypeError: Cannot read property 'then' of null
    at window.onload at (app.asar/app/preload.js:1:382)`

when you close the window on mac and then click the icon in dock to open new window
you get error
`Uncaught Exception:
Error: Object has been destroyed
    at App.app.on (/Applications/WebCatalog.app/Contents/Resources/app.asar/app/index.js:1:2868)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:191:7)`

happens even if you have checked to close the app when last window quits (so that funcionality seems to no longer work)

btw. probably would be nice to add labels to the controls in titlebar with label and shortcut info (ie. Home Alt+H, so the ppl know the shortcuts) or just add one more item to the main menu under Settings where there would be listed available shortcuts (and in future they could be changeable)

(btw i updated some icons in the backend pull, but the webcatalog still displays old ones)

**Comment by Paulser** [comment]
@quanglam2807  4.1.2 Tested on Windows 10 (Will test Ubuntu later). Some icons missing on apps. Also still seems to not install any app from the store.

**Comment by quanglam2807** [comment]
@natrim @Paulser what do you guys  mean with "some icons missing"?

**Comment by quanglam2807** [comment]
@natrim I don't know why but app install works for me :(

**Comment by Paulser** [comment]
@quanglam2807 4.1.2 Tested on Ubuntu 16.04. The App's are working a lot better. I am now able to install Apps that work. The missing icons are not issue anymore on the home page. 

There is a small issue that still present. The app store wants to update an App that does not exists when you press update all Apps it disappears not a real issue. It does seem to come back when you close and reopen the web store.

updateiconsmissing

I will review the Windows version again provide Gif files for you to review.

**Comment by Paulser** [comment]
@quanglam2807 4.1.2 Tested on Windows 10. This seems to be working now. I am now able to install Apps and they work. The missing icons are not issue anymore on the home page and updates page.

**Comment by quanglam2807** [comment]
@Paulser  @natrim 4.1.3 is up. Please test :) https://github.com/webcatalog/webcatalog/releases/tag/v4.1.3

**Comment by natrim** [comment]
@quanglam2807 in 4.1.3 the icons are loading ok (maybe it was just caused by slow net)

app install and update is working now (maybe it was cased by the slow net too?)

the close app on last window quit is still not working
and the error on trying to open new window after the last closes still has error
`Uncaught Exception:
Error: Object has been destroyed
    at App.app.on (/Applications/WebCatalog.app/Contents/Resources/app.asar/app/index.js:1:2945)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:191:7)`
(to reproduce check the "Quit when last window is closed" in settings and quit the app, then start it again and close the last window - it will stay in dock and on click the dock icon the error pops up)

the `Uncaught TypeError: Cannot read property 'then' of null at window.onload at (/Applications/WebCatalog.app/Contents/Resources/app.asar/app/preload.js:1:382)`
is still sometimes poping

**Comment by Paulser** [comment]
Tested: https://github.com/webcatalog/webcatalog/releases/tag/v4.1.3

Windows 10 - Works fine loads icons/apps and runs really well. No issue found on Windows 10.

Ubuntu 16.04 (KDE Neon) - Loading icons/apps on home page is slower than Windows 10 but it still works. It is not bad at all. The app store wants to update two Apps that does not exists when you press update all Apps it disappears. They come back when you close and open the app store.

ubuntunoexistingappsapears

Icon issue on task bar still exists on Ubuntu but I will go into more information on #97.

**Comment by quanglam2807** [comment]
@Paulser @natrim New build: https://github.com/webcatalog/webcatalog/releases/tag/v4.1.4

Please test. :)

**Comment by natrim** [comment]
seems ok for me
edit: @quanglam2807 nope
now you cannot close app on mac if it has not quit on lost window enabled .)
(ie. itz ignoring Cmd+Q, and even right clik in dock and then Quit app (only force quit works))

**Comment by quanglam2807** [comment]
@natrim I can't reproduce the bug. Can you me a little more detail?

Edit: Nevermind. I figured out.

**Comment by Paulser** [comment]
@quanglam2807 

Tested https://github.com/webcatalog/webcatalog/releases/tag/v4.1.4

Ubuntu 16.04 - KDE Neon - User Edition - Plasma 5.8 Desktop

Same issues as reported on v4.1.3 with two Apps that does not exist & Icons missing in task bar. 

I have updated Issue #97

**Comment by quanglam2807** [comment]
@Paulser WebCatalog on Linux is a big mess now. :( I'm working on it.

**Comment by Paulser** [comment]
@quanglam2807 

Lol shame it my main OS. 

I will help with testing when I can. 

Windows 10 works great still at least. 

Thanks for the hard work.

**Comment by quanglam2807** [comment]
@natrim @Paulser new build: https://github.com/webcatalog/webcatalog/releases/tag/v4.1.5. I haven't tested it carefully. But please do.

**Comment by Paulser** [comment]
@quanglam2807 

Tested:  https://github.com/webcatalog/webcatalog/releases/tag/v4.1.5 

Ubuntu 16.04 - Works great for installing apps and uninstalling on first open on web store. 

Two Apps that do not exist issue has been resolved.


Issue #95 still exists. 

New issue when you close and open the web store it does not store what been installed. Applications still seem to work and you can reinstall apps which I think just re-links to your existing apps. You still have control to uninstall the apps just need to reinstall first. 

peek 2017-04-14 14-12

**Comment by natrim** [comment]
on Windows10 the update button is not working
if you have old shortcut and click update, the shortcut gets only removed, not installed

**Comment by quanglam2807** [comment]
@Paulser Temporarily I will move the Linux issues to the next release. My plan is to remove the custom app feature as soon as possible.

**Comment by natrim** [comment]
in 4.1.8 (on W10) the app is still gone during update
missing

although now the shortcuts remians in the path
(it just disappears from webcatalog install until next time you open webcatalog, but its not updated)
¨
so the update is not working .)

**Pull request merged**
