### PR TITLE
WebCatalog 4: Major update

### PR DESCRIPTION
**Pull request by quanglam2807**
- [x] Customize home URL #41 
- [x] Block ads & tracking  #58
- [x] Generate ico & icns client-side.
- [x] Clear storage data when uninstalling.
- [x] Install custom app. #12 
- [x] Inject CSS & JS #13 . 
- [x] Remove Choosy support.

### CODE REVIEW

**Comment by natrim** [comment]
seems very promising 
fluttershy_yay100

**Comment by quanglam2807** [comment]
@natrim And buggy as hell.

**Comment by natrim** [comment]
well it will get better right?
hell was in beta testing phase for several milion years and by now its pretty much topnotch
(i hope it will not take million years for v4 to go out)

**Comment by quanglam2807** [comment]
@natrim @jottr @swrobel @Rediwed 
Alpha build is now ready. Please test :)
https://github.com/webcatalog/webcatalog/releases/tag/v4.0.0

**Comment by natrim** [comment]
the Custom Home URL seems to not work

(plus when i write it puts the cursor to the end of input after every keyup (it does it even for the js and css inputs))

injecting css and js seems to work 

ad blocking seems to not work

custom apps dont work (it just opens store)

tested on W10

**Comment by quanglam2807** [comment]
@natrim I've fixed almost all the bugs you mentioned. New alpha: https://github.com/webcatalog/webcatalog/releases/tag/v4.0.1

**Comment by natrim** [comment]
when i use home in the menu it does not respect the custom homepage

**Comment by quanglam2807** [comment]
@natrim Thank you! Fixed. I'll fix the ad blocker before creating a new build.

**Comment by natrim** [comment]
when adding custom app there is no icon added

**Comment by quanglam2807** [comment]
@natrim I don't get it. You mean you cannot customize the icon?

**Comment by natrim** [comment]
yes, i select icon and install the app,¨

but the icon is empty and it says that the path does not contains any icon

**Comment by quanglam2807** [comment]
@natrim New build is up.

**Comment by natrim** [comment]
icons works now

i cannot test ad blocking cause it does not want to compile the adblocker on win though (some python things)

**Comment by quanglam2807** [comment]
@natrim You need to setup node-gyp. I have updated README.md so you can check. Anyway, 4.0.3 is up :). I think most of the features are now ready.

**Comment by natrim** [comment]
when i enable the adblock then there is cca 15sec delay when the app si not reacting on first page load
(just ´blank white screen and the app is totaly frozen)
subsequent page loads are then ok and adblock is working but when i close it and start anew then the freeze is here again

**Comment by quanglam2807** [comment]
@natrim It's because of electron http://stackoverflow.com/questions/34039130/electron-how-to-parse-a-large-file-without-blocking-render. I'll start migrating to muon after this release. But except that bug, is there anything else? If not, I'll release the update. :)

**Comment by natrim** [comment]
i did not notice any other problem

**Comment by swrobel** [comment]
sorry, didn't get a chance to test but so far it looks great! haven't found a good case to test the adblocker ... facebook ads don't seem to be blocked by it. but it doesn't seem to break anything for me.
screen shot 2017-03-28 at 5 20 44 pm

**Comment by swrobel** [comment]
Oh, actually I did notice an issue. It won't let me pick a `.icns` file as the icon for a Custom App.

**Comment by quanglam2807** [comment]
@swrobel I use https://easylist.to/ to filter ads so maybe the filtering list doesn't include all the facebook endpoints. Also, adding ICNS support is easy so I'll add it in the next update.

**Pull request merged**
