### PR TITLE
WIP: WebCatalog 3.0

### PR DESCRIPTION
**Pull request by quanglam2807**
- [x] Reorganizes code.
- [x] Uses [webview tag](http://electron.atom.io/docs/api/webview-tag/).
- [x] Adds Find in Page #16 .
- [x] Adds Navigation bar #33 . 
- [x] Per-app settings #37 
- [x] Quit app on last window #38

### CODE REVIEW

**Comment by quanglam2807** [comment]
@Rediwed @narim @jottr What do you guy think?

http://www.mediafire.com/file/ye1ndr754s2tje4/WebCatalog-Beta-1-3.0.0.dmg Test build if you guys want to try.

**Comment by natrim** [comment]
controls seems to work nicely

**Comment by Rediwed** [comment]
I'll try it today (can it be ran side-by-side?)

**Comment by quanglam2807** [comment]
@natrim 👍. But for sites like google.com, for a reason, it's a bit laggy. I don't why.

@Rediwed You can rename the old version to something else. But apps installed from WebCatalog use /Application/WebCatalog.app by default.

**Comment by natrim** [comment]
maybe the "did-stop-loading" or "did-start-loading" event triggers multiple times in short order causing some callback mania?
or maybe the webview resizes and rerenders the whole component multiple times?
you could try adding "shouldComponentUpdate" with some checks?

**Comment by quanglam2807** [comment]
@natrim The webview blocks the rendering process (even if I use it outside of React). It's not an issue with Brave. @bbondy can you help, please?

**Comment by quanglam2807** [comment]
@natrim Brave uses a different version of Electron https://github.com/brave/muon. I tested and everything loads much faster. But it's not official so it would take a lot of efforts to rewrite WebCatalog's distribution scripts.

**Review by quanglam2807 — COMMENTED** [review]
#2

**Review by quanglam2807 — COMMENTED** [review]
#38

**Comment by quanglam2807** [comment]
@natrim @Rediwed @swrobel 3.0.0 will be up soon so please try and give me some feedback 👍

**Comment by natrim** [comment]
Seems to worky on Windows, will try it on mac when i get to work on Monday.
schranka 01
Thought there seems to be no nav bar on windows.

**Comment by quanglam2807** [comment]
@natrim The design doesn't work well on Windows so at the moment, it's only available for macOS.

**Comment by swrobel** [comment]
I can't seem to trigger Find in Page w/ CMD+F. Using the beta under Releases.

**Comment by quanglam2807** [comment]
@swrobel That's weird. Which app did you try? It works normally for me.

**Comment by swrobel** [comment]
@quanglam2807 I just tried and it seems that when you "Try" an app it doesn't use the same UI, thus CMD+F didn't work. I tried installing one and it worked this time with 3.0.1 beta (Mac .dmg)

This is great. Thanks so much!

EDIT: I just realized Swipe to Navigate isn't working. I have "Swipe with three fingers" enabled in Trackpad settings and "Swipe to Navigate" is enabled in the Webcatalog app settings. I can go forward/back with the keyboard shortcut or the navigation buttons.

**Comment by quanglam2807** [comment]
@swrobel Thank you for reporting!!! I have fixed it in 3.0.2. 

Also, I'll try to improve the trial mode (or remove it) so the users won't be confused.

**Comment by natrim** [comment]
works ok on mac

btw. is there reason that the app is not using electron auto-updater on MAC?

**Comment by quanglam2807** [comment]
@natrim #10

**Comment by natrim** [comment]
i see, that is easily fixable by using binary to replace the fake
moving the conversation to #10 (theres my solution there)

**Pull request merged**
